// this is for emacs file handling -*- mode: c++; indent-tabs-mode: nil -*-

// -- BEGIN LICENSE BLOCK ----------------------------------------------
// This file is part of the PI-Hexapod Driver.
//
//
// © Copyright 2020 Physik Instrumente (PI) GmbH & Co. KG, Karlsruhe, Germany
// © Copyright 2020 FZI Forschungszentrum Informatik, Karlsruhe, Germany
// -- END LICENSE BLOCK ------------------------------------------------

//----------------------------------------------------------------------
/*!\file
 *
 * This file defines Log Makros for the PiDriver.
 * Swapping this definitions makes it possible to change the drivers logging easily.
 *
 * \author  Christian Eichmann <eichmann@fzi.de>
 * \author  Philip Keller <keller@fzi.de>
 * \date    2020-04-06
 *
 */
//----------------------------------------------------------------------

#include <ros/ros.h>

//@cond DOXYGEN_IGNORE

#define LOG_DEBUG ROS_DEBUG
#define LOG_DEBUG_STREAM ROS_DEBUG_STREAM
#define LOG_DEBUG_NAMED ROS_DEBUG_NAMED
#define LOG_DEBUG_STREAM_NAMED ROS_DEBUG_STREAM_NAMED
#define LOG_DEBUG_COND ROS_DEBUG_COND
#define LOG_DEBUG_STREAM_COND ROS_DEBUG_STREAM_COND
#define LOG_DEBUG_COND_NAMED ROS_DEBUG_COND_NAMED
#define LOG_DEBUG_STREAM_COND_NAMED ROS_DEBUG_STREAM_COND_NAMED
#define LOG_DEBUG_ONCE ROS_DEBUG_ONCE
#define LOG_DEBUG_STREAM_ONCE ROS_DEBUG_STREAM_ONCE
#define LOG_DEBUG_ONCE_NAMED ROS_DEBUG_ONCE_NAMED
#define LOG_DEBUG_STREAM_ONCE_NAMED ROS_DEBUG_STREAM_ONCE_NAMED
#define LOG_DEBUG_THROTTLE ROS_DEBUG_THROTTLE
#define LOG_DEBUG_STREAM_THROTTLE ROS_DEBUG_STREAM_THROTTLE
#define LOG_DEBUG_THROTTLE_NAMED ROS_DEBUG_THROTTLE_NAMED
#define LOG_DEBUG_STREAM_THROTTLE_NAMED ROS_DEBUG_STREAM_THROTTLE_NAMED
#define LOG_DEBUG_DELAYED_THROTTLE ROS_DEBUG_DELAYED_THROTTLE
#define LOG_DEBUG_STREAM_DELAYED_THROTTLE ROS_DEBUG_STREAM_DELAYED_THROTTLE
#define LOG_DEBUG_DELAYED_THROTTLE_NAMED ROS_DEBUG_DELAYED_THROTTLE_NAMED
#define LOG_DEBUG_STREAM_DELAYED_THROTTLE_NAMED ROS_DEBUG_STREAM_DELAYED_THROTTLE_NAMED
#define LOG_DEBUG_FILTER ROS_DEBUG_FILTER
#define LOG_DEBUG_STREAM_FILTER ROS_DEBUG_STREAM_FILTER
#define LOG_DEBUG_FILTER_NAMED ROS_DEBUG_FILTER_NAMED
#define LOG_DEBUG_STREAM_FILTER_NAMED ROS_DEBUG_STREAM_FILTER_NAMED

#define LOG_INFO ROS_INFO
#define LOG_INFO_STREAM ROS_INFO_STREAM
#define LOG_INFO_NAMED ROS_INFO_NAMED
#define LOG_INFO_STREAM_NAMED ROS_INFO_STREAM_NAMED
#define LOG_INFO_COND ROS_INFO_COND
#define LOG_INFO_STREAM_COND ROS_INFO_STREAM_COND
#define LOG_INFO_COND_NAMED ROS_INFO_COND_NAMED
#define LOG_INFO_STREAM_COND_NAMED ROS_INFO_STREAM_COND_NAMED
#define LOG_INFO_ONCE ROS_INFO_ONCE
#define LOG_INFO_STREAM_ONCE ROS_INFO_STREAM_ONCE
#define LOG_INFO_ONCE_NAMED ROS_INFO_ONCE_NAMED
#define LOG_INFO_STREAM_ONCE_NAMED ROS_INFO_STREAM_ONCE_NAMED
#define LOG_INFO_THROTTLE ROS_INFO_THROTTLE
#define LOG_INFO_STREAM_THROTTLE ROS_INFO_STREAM_THROTTLE
#define LOG_INFO_THROTTLE_NAMED ROS_INFO_THROTTLE_NAMED
#define LOG_INFO_STREAM_THROTTLE_NAMED ROS_INFO_STREAM_THROTTLE_NAMED
#define LOG_INFO_DELAYED_THROTTLE ROS_INFO_DELAYED_THROTTLE
#define LOG_INFO_STREAM_DELAYED_THROTTLE ROS_INFO_STREAM_DELAYED_THROTTLE
#define LOG_INFO_DELAYED_THROTTLE_NAMED ROS_INFO_DELAYED_THROTTLE_NAMED
#define LOG_INFO_STREAM_DELAYED_THROTTLE_NAMED ROS_INFO_STREAM_DELAYED_THROTTLE_NAMED
#define LOG_INFO_FILTER ROS_INFO_FILTER
#define LOG_INFO_STREAM_FILTER ROS_INFO_STREAM_FILTER
#define LOG_INFO_FILTER_NAMED ROS_INFO_FILTER_NAMED
#define LOG_INFO_STREAM_FILTER_NAMED ROS_INFO_STREAM_FILTER_NAMED

#define LOG_WARN ROS_WARN
#define LOG_WARN_STREAM ROS_WARN_STREAM
#define LOG_WARN_NAMED ROS_WARN_NAMED
#define LOG_WARN_STREAM_NAMED ROS_WARN_STREAM_NAMED
#define LOG_WARN_COND ROS_WARN_COND
#define LOG_WARN_STREAM_COND ROS_WARN_STREAM_COND
#define LOG_WARN_COND_NAMED ROS_WARN_COND_NAMED
#define LOG_WARN_STREAM_COND_NAMED ROS_WARN_STREAM_COND_NAMED
#define LOG_WARN_ONCE ROS_WARN_ONCE
#define LOG_WARN_STREAM_ONCE ROS_WARN_STREAM_ONCE
#define LOG_WARN_ONCE_NAMED ROS_WARN_ONCE_NAMED
#define LOG_WARN_STREAM_ONCE_NAMED ROS_WARN_STREAM_ONCE_NAMED
#define LOG_WARN_THROTTLE ROS_WARN_THROTTLE
#define LOG_WARN_STREAM_THROTTLE ROS_WARN_STREAM_THROTTLE
#define LOG_WARN_THROTTLE_NAMED ROS_WARN_THROTTLE_NAMED
#define LOG_WARN_STREAM_THROTTLE_NAMED ROS_WARN_STREAM_THROTTLE_NAMED
#define LOG_WARN_DELAYED_THROTTLE ROS_WARN_DELAYED_THROTTLE
#define LOG_WARN_STREAM_DELAYED_THROTTLE ROS_WARN_STREAM_DELAYED_THROTTLE
#define LOG_WARN_DELAYED_THROTTLE_NAMED ROS_WARN_DELAYED_THROTTLE_NAMED
#define LOG_WARN_STREAM_DELAYED_THROTTLE_NAMED ROS_WARN_STREAM_DELAYED_THROTTLE_NAMED
#define LOG_WARN_FILTER ROS_WARN_FILTER
#define LOG_WARN_STREAM_FILTER ROS_WARN_STREAM_FILTER
#define LOG_WARN_FILTER_NAMED ROS_WARN_FILTER_NAMED
#define LOG_WARN_STREAM_FILTER_NAMED ROS_WARN_STREAM_FILTER_NAMED

#define LOG_ERROR ROS_ERROR
#define LOG_ERROR_STREAM ROS_ERROR_STREAM
#define LOG_ERROR_NAMED ROS_ERROR_NAMED
#define LOG_ERROR_STREAM_NAMED ROS_ERROR_STREAM_NAMED
#define LOG_ERROR_COND ROS_ERROR_COND
#define LOG_ERROR_STREAM_COND ROS_ERROR_STREAM_COND
#define LOG_ERROR_COND_NAMED ROS_ERROR_COND_NAMED
#define LOG_ERROR_STREAM_COND_NAMED ROS_ERROR_STREAM_COND_NAMED
#define LOG_ERROR_ONCE ROS_ERROR_ONCE
#define LOG_ERROR_STREAM_ONCE ROS_ERROR_STREAM_ONCE
#define LOG_ERROR_ONCE_NAMED ROS_ERROR_ONCE_NAMED
#define LOG_ERROR_STREAM_ONCE_NAMED ROS_ERROR_STREAM_ONCE_NAMED
#define LOG_ERROR_THROTTLE ROS_ERROR_THROTTLE
#define LOG_ERROR_STREAM_THROTTLE ROS_ERROR_STREAM_THROTTLE
#define LOG_ERROR_THROTTLE_NAMED ROS_ERROR_THROTTLE_NAMED
#define LOG_ERROR_STREAM_THROTTLE_NAMED ROS_ERROR_STREAM_THROTTLE_NAMED
#define LOG_ERROR_DELAYED_THROTTLE ROS_ERROR_DELAYED_THROTTLE
#define LOG_ERROR_STREAM_DELAYED_THROTTLE ROS_ERROR_STREAM_DELAYED_THROTTLE
#define LOG_ERROR_DELAYED_THROTTLE_NAMED ROS_ERROR_DELAYED_THROTTLE_NAMED
#define LOG_ERROR_STREAM_DELAYED_THROTTLE_NAMED ROS_ERROR_STREAM_DELAYED_THROTTLE_NAMED
#define LOG_ERROR_FILTER ROS_ERROR_FILTER
#define LOG_ERROR_STREAM_FILTER ROS_ERROR_STREAM_FILTER
#define LOG_ERROR_FILTER_NAMED ROS_ERROR_FILTER_NAMED
#define LOG_ERROR_STREAM_FILTER_NAMED ROS_ERROR_STREAM_FILTER_NAMED

#define LOG_FATAL ROS_FATAL
#define LOG_FATAL_STREAM ROS_FATAL_STREAM
#define LOG_FATAL_NAMED ROS_FATAL_NAMED
#define LOG_FATAL_STREAM_NAMED ROS_FATAL_STREAM_NAMED
#define LOG_FATAL_COND ROS_FATAL_COND
#define LOG_FATAL_STREAM_COND ROS_FATAL_STREAM_COND
#define LOG_FATAL_COND_NAMED ROS_FATAL_COND_NAMED
#define LOG_FATAL_STREAM_COND_NAMED ROS_FATAL_STREAM_COND_NAMED
#define LOG_FATAL_ONCE ROS_FATAL_ONCE
#define LOG_FATAL_STREAM_ONCE ROS_FATAL_STREAM_ONCE
#define LOG_FATAL_ONCE_NAMED ROS_FATAL_ONCE_NAMED
#define LOG_FATAL_STREAM_ONCE_NAMED ROS_FATAL_STREAM_ONCE_NAMED
#define LOG_FATAL_THROTTLE ROS_FATAL_THROTTLE
#define LOG_FATAL_STREAM_THROTTLE ROS_FATAL_STREAM_THROTTLE
#define LOG_FATAL_THROTTLE_NAMED ROS_FATAL_THROTTLE_NAMED
#define LOG_FATAL_STREAM_THROTTLE_NAMED ROS_FATAL_STREAM_THROTTLE_NAMED
#define LOG_FATAL_DELAYED_THROTTLE ROS_FATAL_DELAYED_THROTTLE
#define LOG_FATAL_STREAM_DELAYED_THROTTLE ROS_FATAL_STREAM_DELAYED_THROTTLE
#define LOG_FATAL_DELAYED_THROTTLE_NAMED ROS_FATAL_DELAYED_THROTTLE_NAMED
#define LOG_FATAL_STREAM_DELAYED_THROTTLE_NAMED ROS_FATAL_STREAM_DELAYED_THROTTLE_NAMED
#define LOG_FATAL_FILTER ROS_FATAL_FILTER
#define LOG_FATAL_STREAM_FILTER ROS_FATAL_STREAM_FILTER
#define LOG_FATAL_FILTER_NAMED ROS_FATAL_FILTER_NAMED
#define LOG_FATAL_STREAM_FILTER_NAMED ROS_FATAL_STREAM_FILTER_NAMED

//@endcond
